# You may assign one main APIs for each "imggen", "textgen", "ttsgen" (defined in "all_apis" - below this section)
bot_api_functions:
  # Special endpoints which the bot can use in main functions. To disable any, use value null or comment out the line.
  # Note: Main API names / endpoint names are case sensitive!
  imggen:
    api_name: Stable Diffusion WebUI
    post_txt2img_endpoint_name: Post txt2img
    post_img2img_endpoint_name: Post img2img
    get_progress_endpoint_name: Get Progress
    post_png_info_endpoint_name: Post PNG Info
    post_options_endpoint_name: Post Options
    get_imgmodels_endpoint_name: Get ImgModels
    get_controlnet_models_endpoint_name: Get Cnet Models
    get_controlnet_control_types_endpoint_name: Get Cnet Control Types
    post_server_restart_endpoint_name: Post Server Restart
  # API for Text Gen is WIP. Bot currently cannot use textgen API for main functions.
  textgen: {} # placeholder.
  # API for TTS is WIP. These settings are currently limited to the '/speak' command (will not work for message requests)
  ttsgen:
    api_name: AllTalk TTS v2
    get_voices_endpoint_name: Get TTS Voices
    post_generate_endpoint_name: Post TTS Generate


# Define any APIs to use with the bot
all_apis:
  # You may define any number of APIs and Endpoints here (a list of dictionaries), making them available to use for various bot functions,
  #   including the "main" apis above, the Tags system (dict_tags.yaml), user defined commands (dict_commands.yaml), etc.
  - name: Stable Diffusion WebUI
    url: http://127.0.0.1:7860
    enabled: true
    default_headers: {Content-Type: application/json}
    default_timeout: 10 # seconds to wait before aborting api call
    auth: null # {username: myuser, password: mypass} # dict format with keys 'username' and 'password'
    # Add any endpoints that you may use for bot functions (Tags system, user commands, etc)
    endpoints:
      - {name: Post txt2img, path: /sdapi/v1/txt2img, method: POST, response_type: json, retry: 1, payload: sd-webui.yaml, timeout: 120}
      - {name: Post img2img, path: /sdapi/v1/img2img, method: POST, timeout: 120}
      - {name: Get Progress, path: /sdapi/v1/progress, method: GET}
      - {name: Post PNG Info, path: /sdapi/v1/png-info, method: POST}
      - {name: Get ImgModels, path: /sdapi/v1/sd-models, method: GET}
      - {name: Get Options, path: /sdapi/v1/options, method: GET}
      - {name: Post Options, path: /sdapi/v1/options, method: POST}
      - {name: Get Cnet Models, path: /controlnet/model_list, method: GET}
      - {name: Get Cnet Control Types, path: /controlnet/control_types, method: GET}
      - {name: Post Server Restart, path: /sdapi/v1/server-restart, method: POST, retry: 0}

  - name: Text Generation WebUI
    url: http://127.0.0.1:7861
    enabled: false
    default_headers: {Content-Type: application/json}
    default_timeout: 60
    auth: null
    endpoints: []

  - name: AllTalk TTS v2
    url: http://127.0.0.1:7851
    enabled: false
    default_headers:
      Content-Type: application/x-www-form-urlencoded
    default_timeout: 60
    auth: null
    endpoints:
      - {name: Get TTS Voices, path: /api/voices, method: GET, timeout: 10}
      - {name: Post TTS Generate, path: /api/tts-generate, method: POST}

  - name: Example image gen API
    url: http://127.0.0.1:7869
    enabled: false
    default_headers: {Content-Type: application/json}
    default_timeout: 60
    auth: null
    endpoints:
      - name: Generate image
        path: /api/imggen
        method: POST
        response_handling:
          preset: Decode base64 and save # from preset below
          post_process:
            - preset: Extract metadata
          filename_prefix: ex_gen # overrides value in the preset


# Define a list of processing presets here, which can be injected in 'response_handling' or in any 'post_process' steps.
response_handling_presets:
  - name: Decode base64 and save
    type: base64
    output_key: images      # key in JSON to extract from
    output_format: png      # only used if type is base64
    save_to: images         # where to save files if media_file or base64
    filename_prefix: img_gen
  
  - name: Extract metadata
    endpoint_name: Post PNG Info
    payload_key: image
    response_key: info
    metadata_field: parameters
